### ISSUE TITLE
Build Scenario 5.3 - Webapp Deployment

### ISSUE THREAD

**Issue by Andu1391** [marianleica/azrez#15]
Deployment - ok; Except being prompted about not having the Extend Location provider registered. 
Added - az provider register -n Microsoft.ExtendedLocation --wait
Suggestion - adding the provider registration before?
Second deployment - OK full

Step: 2024-11-05T10-31-47Z: Checking Microsoft.ExtendedLocation RP Registration state for this Subscription, and get OID, if registered
'Custom-locations' feature couldn't be enabled on this cluster as the pre-requisite registration of 'Microsoft.ExtendedLocation' was not met. More details for enabling this feature later on this cluster can be found here - https://aka.ms/EnableCustomLocations

Microsoft.ExtendedLocation provider is not registered.  Run `az provider register -n Microsoft.ExtendedLocation --wait`.

(ResourceNotFound) The Resource 'Microsoft.ExtendedLocation/customLocations/arc-location' under resource group 'azrez' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
ERROR: (ResourceNotFound) The Resource 'Microsoft.ExtendedLocation/customLocations/arc-location' under resource group 'azrez' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

Webapp Deployment: 

	- Here I had a bit of trouble. 
	- Could not zip up the package.zip via that command, as it did not work & I did not know how to make it work, so I made the .zip manually.

The webapp webapp-6671 is now created.
To provide code to the webapp, you may use the example below:

git clone https://github.com/Azure-Samples/nodejs-docs-hello-world
cd nodejs-docs-hello-world
zip -r package.zip .
az webapp deployment source config-zip --resource-group azrez --name webapp-6671 --src package.zip

	- Deployment: 

$ az webapp deployment source config-zip --resource-group azrez --name webapp-6671 --src package.7z
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
The behavior of this command has been altered by the following extension: appservice-kube
Getting scm site credentials for zip deployment
<urllib3.connection.HTTPSConnection object at 0x000001D7A42FD690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

**Comment by marianleica** [comment]
Testing...

**Comment by marianleica** [comment]
The scope of the scenario here is to have the webapp created and running in an arc-enabled kubernetes cluster via the appservice extension.

Indeed, the commands:

```
git clone https://github.com/Azure-Samples/nodejs-docs-hello-world
cd nodejs-docs-hello-world
zip -r package.zip .
az webapp deployment source config-zip --resource-group azrez --name webapp-6671 --src package.zip
```

are requiring 'git' to be installed, then 'zip' is on Linux
leaving it by design for now for the user to add their code if required
